apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-datacenter
  namespace: tomcat-namespace-datacenter
spec:
  type: NodePort
  selector:
    app: tomcat-datacenter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32227
